# Generated by Django 3.1.5 on 2021-01-20 23:53

from django.db import migrations, models
import semifinals.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('upstream_id', models.IntegerField(blank=True, help_text="ID de l'ER sur le site Prologin", null=True)),
                ('display_name', models.CharField(help_text='Nom affiché de la session', max_length=100)),
                ('date_start', models.DateTimeField(verbose_name='Début')),
                ('date_end', models.DateTimeField(verbose_name='Fin')),
                ('status', models.IntegerField(choices=[(0, 'Not Published'), (1, 'Teased'), (2, 'Open'), (3, 'Submissions Closed')], verbose_name='Statut')),
                ('subject', models.FileField(blank=True, null=True, upload_to=semifinals.models.get_session_subject_path)),
                ('contestant_instructions', models.TextField(max_length=1000)),
            ],
        ),
    ]
