# Generated by Django 3.1.5 on 2021-02-20 09:20

from django.db import migrations, models
import written_exams.models


class Migration(migrations.Migration):

    dependencies = [
        ('written_exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'permissions': [('can_export_submissions', 'User can export submissions')]},
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(storage=written_exams.models.OverrideStorage(), upload_to=written_exams.models.get_path),
        ),
    ]
