# Generated by Django 3.1.5 on 2021-02-11 22:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('meet_link', models.URLField(blank=True, null=True, verbose_name='Google Meet link')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('status', models.IntegerField(choices=[(0, 'Not Published'), (1, 'Slot Instanciation'), (2, 'Contestant Choice'), (3, 'Locked')])),
                ('upstream_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.session')),
            ],
        ),
        migrations.CreateModel(
            name='SlotInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestant', models.ForeignKey(blank=True, limit_choices_to={'is_staff': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.interviewer')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='interviews.slot')),
            ],
            options={
                'unique_together': {('interviewer', 'slot'), ('slot', 'contestant')},
            },
        ),
        migrations.CreateModel(
            name='InterviewScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(help_text='Entier compris entre 0 et 5', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('comments', models.TextField(max_length=400, verbose_name="Commentaires sur l'entretien")),
                ('contestant', models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.session')),
            ],
            options={
                'unique_together': {('session', 'contestant')},
            },
        ),
    ]
