# Generated by Django 3.1.5 on 2021-03-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewer_email_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ('date_start',)},
        ),
        migrations.AlterModelOptions(
            name='slotinstance',
            options={'ordering': ('slot',)},
        ),
    ]
