# Generated by Django 3.1.5 on 2021-03-10 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_auto_20210310_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewscore',
            name='grade',
            field=models.DecimalField(decimal_places=2, help_text='Nombre décimal compris entre 0 et 5 (Format xx,x)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Note'),
        ),
    ]
