# Generated by Django 3.1.5 on 2021-01-24 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import se_forms.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('subject_path', models.CharField(help_text='Path to the subject relative to PROLOGIN_FORMS_REPOSITORY', max_length=200, validators=[se_forms.validators.validate_form])),
                ('display_name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='se_forms.forminstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user answers',
                'verbose_name_plural': 'user answers',
                'unique_together': {('user', 'form')},
            },
        ),
    ]
